(load! "modules/ui")
(load! "modules/editor")
(load! "modules/lang-verilog")
(load! "modules/lang-go")
(load! "modules/lang-jinja2")
(load! "modules/org-mode")
(load! "modules/projects")
(load! "modules/tools")

;; Machine/site-local overlay: untracked, lives outside the dotfiles repo.
(let ((local-dir (expand-file-name "~/.config/doom-local/")))
  (setq custom-file (expand-file-name "custom.el" local-dir))
  (when (file-directory-p local-dir)
    (dolist (f (sort (file-expand-wildcards (concat local-dir "*.el")) #'string<))
      (unless (string-suffix-p "custom.el" f)
        (load f nil t)))
    (let ((snips (concat local-dir "snippets")))
      (when (file-directory-p snips)
        (after! yasnippet (add-to-list 'yas-snippet-dirs snips t))))))
